[workspace]
name = "sinteractive"
description = "Documentation site for sinteractive"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[dependencies]
python = ">=3.11"
zensical = "*"

[tasks]
docs = "zensical serve"
build = "zensical build"
deploy = "zensical build --clean"
